# Phase 3: map destinations and emit the move script the user runs.
#
# dundee executes nothing here. It writes a manifest and a self-contained shell
# script; the user remounts the library read-write, runs the script, and
# dd_run_move() reconciles the store against what actually happened. Source and
# destination are both inside the mounted library, so every move is a rename
# within one share rather than a copy over the wire.

#' Compute the destination path for a photo.
#'
#' @param rel_path Path relative to the library root.
#' @param preferred Logical; TRUE routes to the preferred root.
#' @param cfg A config list (uses `preferred_root`, `nonpreferred_root`).
#' @return The destination absolute path, preserving the relative tree.
#' @export
dd_map_dest <- function(rel_path, preferred, cfg) {
  root <- ifelse(preferred, cfg$preferred_root, cfg$nonpreferred_root)
  file.path(root, rel_path)
}

# Single-quote for the shell, escaping embedded single quotes, so a path with
# spaces or awkward characters survives verbatim.
dd_shq <- function(x) paste0("'", gsub("'", "'\\\\''", x), "'")

# Warn when the destination trees are not pruned during enumeration. They live
# inside library_root (dd_require_move_config enforces that), so once the script
# has run, the next inventory would walk them and file every moved photo as a
# new one. 10-enumerate.sh prunes by -name at any depth, so any component of the
# destination's relative path being in `cruft` is enough.
dd_warn_dest_cruft <- function(cfg) {
  roots <- c(preferred_root = cfg$preferred_root,
             nonpreferred_root = cfg$nonpreferred_root)
  root <- sub("/+$", "", cfg$library_root)
  unpruned <- character(0)
  for (k in names(roots)) {
    rel <- substring(roots[[k]], nchar(root) + 2L)
    parts <- setdiff(strsplit(rel, "/", fixed = TRUE)[[1]], "")
    if (!length(parts) || !any(parts %in% cfg$cruft)) unpruned <- c(unpruned, k)
  }
  if (!length(unpruned)) return(invisible(FALSE))
  warning("dundee: the move destinations are inside library_root but no ",
          "component of them appears in `cruft`:\n  ",
          paste(sprintf("%s: %s", unpruned, roots[unpruned]), collapse = "\n  "),
          "\n  Re-running inventory after the move would enumerate the moved ",
          "copies as new photos.\n  Add the destination directory name to ",
          "`cruft` in config.yml.", call. = FALSE)
  invisible(TRUE)
}

# The generated script's header: usage, preflight and the do_move worker every
# row below it calls. Kept as one block so the per-move lines stay short.
#
# One failing move must not abandon the rest of the batch: when ssh streamed the
# whole thing with nobody watching, aborting on the first error was right, but
# this is run by hand against the user's own library. That resilience lives in
# do_move -- it captures each failure, records it, and always returns 0 -- and
# NOT in dropping `set -e`, which stays on to catch anything going wrong in the
# preflight or between the rows. The exit status at the end reports the count.
dd_move_script_header <- function(cfg, n) {
  lib <- cfg$library_root
  c(
    "#!/usr/bin/env bash",
    sprintf("# Generated by dundee dd_plan_moves() on %s.",
            format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
    "#",
    sprintf("# Moves %d photo(s) inside the library:", n),
    sprintf("#   library       %s", lib),
    sprintf("#   preferred     %s", cfg$preferred_root),
    sprintf("#   non-preferred %s", cfg$nonpreferred_root),
    "#",
    "# Every path below is on this machine, under the library mount. Source and",
    "# destination share one mount, so each move is a rename: no bytes are",
    "# copied, however large the photo.",
    "#",
    "#   bash moves.sh --dry-run              rehearse; touches nothing",
    "#   bash moves.sh                        move the non-preferred copies out",
    "#   bash moves.sh --include-preferred    also relocate the preferred copies",
    "#",
    "# By default each group's preferred copy stays exactly where it is. That is",
    "# already a library without duplicates: only the rejects are quarantined,",
    "# and the folders you know are untouched.",
    "#",
    "# The library is normally mounted read-only, and this script will refuse to",
    "# run until it is writable. Remount it read-write first, and consider",
    "# remounting read-only again once dd_run_move() has reconciled the store.",
    "#",
    "# Re-runnable: a move whose source is already gone is counted and skipped,",
    "# and mv -n never overwrites. Completed moves are appended to",
    "# moves.done.tsv beside this script, failures to moves.failed.tsv, and",
    "# preferred copies left alone to moves.kept.tsv.",
    "",
    "set -euo pipefail",
    "",
    'here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    sprintf("library=%s", dd_shq(lib)),
    'done_log="$here/moves.done.tsv"',
    'fail_log="$here/moves.failed.tsv"',
    'kept_log="$here/moves.kept.tsv"',
    "",
    '# A loop, not a case on $1: the two flags have to compose.',
    'dry=no',
    'include_preferred=no',
    'while [[ "$#" -gt 0 ]]; do',
    '  case "$1" in',
    '    --dry-run) dry=yes ;;',
    '    --include-preferred) include_preferred=yes ;;',
    '    *)',
    '      printf \'usage: %s [--dry-run] [--include-preferred]\\n\' "$0" >&2',
    '      printf \'  default: move the non-preferred copies out and leave\\n\' >&2',
    '      printf \'           each group\'"\'"\'s preferred copy where it is\\n\' >&2',
    '      exit 2 ;;',
    '  esac',
    '  shift',
    'done',
    "",
    '# Preflight, before anything moves.',
    'if [[ ! -d "$library" ]]; then',
    '  printf \'library is not there: %s\\n  (is the share mounted?)\\n\' \\',
    '         "$library" >&2',
    '  exit 1',
    'fi',
    '# An empty mount point means the share is NOT mounted. Moving into it would',
    '# scatter the library across the local disk, and the sources would be gone.',
    'if [[ -z "$(ls -A "$library" 2>/dev/null)" ]]; then',
    '  printf \'library is empty: %s\\n  (the share is not mounted)\\n\' \\',
    '         "$library" >&2',
    '  exit 1',
    'fi',
    'if [[ "$dry" == no && ! -w "$library" ]]; then',
    '  printf \'library is read-only: %s\\n\' "$library" >&2',
    '  printf \'  remount it read-write, or re-run with --dry-run\\n\' >&2',
    '  exit 1',
    'fi',
    "",
    'stamp="$(date -u +%Y-%m-%dT%H:%M:%S)"',
    'moved=0; already=0; missing=0; failed=0; kept=0; shown=0',
    "",
    'do_move() {',
    '  local id="$1" src="$2" dest="$3" err',
    '  if [[ ! -e "$src" ]]; then',
    '    # Already gone. At its destination means a previous run did it; not',
    '    # there means something else removed it, which is not ours to report',
    '    # as done -- dd_run_move() draws the same distinction.',
    '    if [[ -e "$dest" ]]; then already=$((already + 1))',
    '    else missing=$((missing + 1)); fi',
    '    return 0',
    '  fi',
    '  if [[ -e "$dest" ]]; then',
    '    # Source and destination both present: mv -n would silently do nothing',
    '    # and report success, so call it what it is. A rehearsal counts it but',
    '    # writes nothing -- --dry-run must leave the disk exactly as it found it.',
    '    failed=$((failed + 1))',
    '    if [[ "$dry" == no ]]; then',
    '      printf \'%s\\t%s\\t%s\\t%s\\n\' "$id" "$src" "$dest" \\',
    '             "destination already exists" >> "$fail_log"',
    '    fi',
    '    return 0',
    '  fi',
    '  if [[ "$dry" == yes ]]; then',
    '    moved=$((moved + 1))',
    '    if [[ "$shown" -lt 20 ]]; then',
    '      printf "  mv %s\\n     %s\\n" "$src" "$dest"',
    '      shown=$((shown + 1))',
    '    fi',
    '    return 0',
    '  fi',
    '  if ! err="$(mkdir -p "$(dirname "$dest")" 2>&1)"; then',
    '    printf \'%s\\t%s\\t%s\\t%s\\n\' "$id" "$src" "$dest" "${err//[[:space:]]/ }" \\',
    '      >> "$fail_log"',
    '    failed=$((failed + 1))',
    '    return 0',
    '  fi',
    '  if ! err="$(mv -n "$src" "$dest" 2>&1)"; then',
    '    printf \'%s\\t%s\\t%s\\t%s\\n\' "$id" "$src" "$dest" "${err//[[:space:]]/ }" \\',
    '      >> "$fail_log"',
    '    failed=$((failed + 1))',
    '    return 0',
    '  fi',
    '  printf \'%s\\t%s\\t%s\\t%s\\n\' "$id" "$src" "$dest" "$stamp" >> "$done_log"',
    '  moved=$((moved + 1))',
    '}',
    "",
    '# The two tiers, named so that every row below says which it is.',
    'move_nonpreferred() { do_move "$@"; }',
    "",
    'move_preferred() {',
    '  # Pulling the rejects out is already a library without duplicates, so the',
    '  # winner stays put unless asked otherwise. Recorded either way: dundee has',
    '  # no other way to tell "left alone on purpose" from "did not move".',
    '  if [[ "$include_preferred" == no ]]; then',
    '    kept=$((kept + 1))',
    '    if [[ "$dry" == no ]]; then',
    '      printf \'%s\\t%s\\t%s\\t%s\\n\' "$1" "$2" "$3" "$stamp" >> "$kept_log"',
    '    fi',
    '    return 0',
    '  fi',
    '  do_move "$@"',
    '}',
    "",
    'if [[ "$dry" == yes ]]; then printf \'DRY RUN - nothing will be moved.\\n\\n\'; fi',
    ""
  )
}

dd_move_script_footer <- function(cfg) {
  c(
    "",
    'if [[ "$moved" -gt "$shown" && "$dry" == yes ]]; then',
    '  printf \'  ... %d more\\n\' "$((moved - shown))"',
    'fi',
    'if [[ "$dry" == yes ]]; then',
    '  printf \'\\n%d to move, %d already at destination, %d source(s) missing, \' \\',
    '         "$moved" "$already" "$missing"',
    '  printf \'%d blocked.\\n\' "$failed"',
    '  if [[ "$kept" -gt 0 ]]; then',
    '    printf \'%d preferred copy(ies) would stay in place.\\n\' "$kept"',
    '  fi',
    '  printf \'Nothing was moved. Re-run without --dry-run to perform them.\\n\'',
    '  exit 0',
    'fi',
    'printf \'%d moved, %d already at destination, %d source(s) missing, \' \\',
    '       "$moved" "$already" "$missing"',
    'printf \'%d failed.\\n\' "$failed"',
    'if [[ "$kept" -gt 0 ]]; then',
    '  printf \'%d preferred copy(ies) left in place.\\n\' "$kept"',
    '  printf \'  (pass --include-preferred to relocate those too)\\n\'',
    'fi',
    'printf \'receipt: %s\\n\' "$done_log"',
    'if [[ "$failed" -gt 0 ]]; then printf \'failures: %s\\n\' "$fail_log"; fi',
    sprintf("printf 'next: dundee move %%s\\n' %s",
            dd_shq(cfg$work_dir)),
    'if [[ "$failed" -gt 0 ]]; then exit 1; fi'
  )
}

#' Plan moves for all decided photos and emit a manifest + shell script.
#'
#' Writes nothing destructive and touches nothing in the library: produces a TSV
#' manifest, a self-contained shell script for you to review and run, and
#' records planned rows in the `moves` table. Re-runnable.
#'
#' The script takes `--dry-run`, refuses to start unless the library is mounted
#' and writable, and appends every completed move to `moves.done.tsv` beside
#' itself. [dd_run_move()] reads that afterwards to mark the batch done.
#'
#' @param con A DBIConnection.
#' @param cfg A config list.
#' @param manifest_path Output TSV path (default under `work_dir`).
#' @param script_path Output shell script path (default under `work_dir`).
#' @param quiet Logical; suppress the per-row progress bar.
#' @return The manifest data.frame, invisibly.
#' @export
dd_plan_moves <- function(con, cfg,
                          manifest_path = file.path(cfg$work_dir,
                                                    "moves.tsv"),
                          script_path = file.path(cfg$work_dir,
                                                  "moves.sh"),
                          quiet = FALSE) {
  dec <- DBI::dbGetQuery(con, "
    SELECT d.photo_id, d.preferred, p.path, p.rel_path
      FROM decisions d JOIN photos p USING (photo_id)
  ")
  # Drop rows whose decision has since been withdrawn; the upsert below only
  # ever adds or updates, so without this they linger and inflate dd_status().
  # 'kept' goes with 'planned': it records a decision not to move, not a move
  # that happened, so it must not outlive the decision that produced it. Rows
  # already marked done are history and stay.
  DBI::dbExecute(con, "DELETE FROM moves
                        WHERE state IN ('planned', 'kept')
                          AND photo_id NOT IN (SELECT photo_id FROM decisions)")
  if (nrow(dec) == 0L) {
    message("No decisions to plan.")
    return(invisible(dec[0, ]))
  }
  dd_warn_dest_cruft(cfg)
  # The store already holds the path the script will use: there is no server
  # side any more, so no translation step either.
  manifest <- data.frame(
    photo_id = dec$photo_id, preferred = dec$preferred,
    src = dec$path,
    dest = dd_map_dest(dec$rel_path, dec$preferred == 1L, cfg),
    stringsAsFactors = FALSE
  )

  # Paths are UTF-8 (see dd_b64dec) and must reach disk as exactly those bytes.
  # write.table() transliterates to the native encoding first -- under a C
  # locale that writes escapes instead of the filename -- and fileEncoding=
  # only double-converts a string that is already marked UTF-8. So format the
  # rows here and write bytes, as the move script below also does.
  writeLines(c(paste(names(manifest), collapse = "\t"),
               do.call(paste, c(unname(manifest), sep = "\t"))),
             manifest_path, useBytes = TRUE)

  lines <- dd_move_script_header(cfg, nrow(manifest))
  pb <- dd_progress(nrow(manifest), "plan", quiet = quiet)
  rows <- character(nrow(manifest))
  for (i in seq_len(nrow(manifest))) {
    rows[i] <- sprintf("%s %d %s %s",
                       if (manifest$preferred[i] == 1L) "move_preferred   "
                       else "move_nonpreferred",
                       manifest$photo_id[i],
                       dd_shq(manifest$src[i]), dd_shq(manifest$dest[i]))
    pb$tick()
  }
  pb$done()
  # useBytes: the lines carry UTF-8 paths, and the shell wants those bytes
  # verbatim whatever locale the plan happened to be generated under.
  writeLines(c(lines, rows, dd_move_script_footer(cfg)), script_path,
             useBytes = TRUE)
  Sys.chmod(script_path, "0755")

  # The receipts describe the plan being replaced. Left in place, a stale one
  # would re-credit a photo that has since been moved back.
  unlink(file.path(dirname(script_path),
                   c("moves.done.tsv", "moves.failed.tsv", "moves.kept.tsv")))

  # Record planned rows (idempotent upsert).
  dd_upsert(con, "moves",
            data.frame(photo_id = manifest$photo_id, src = manifest$src,
                       dest = manifest$dest, state = "planned",
                       moved_at = NA_character_, stringsAsFactors = FALSE),
            key_cols = "photo_id")

  npref <- sum(manifest$preferred == 1L)
  message(sprintf("Planned %d moves (%d non-preferred, %d preferred) -> %s",
                  nrow(manifest), nrow(manifest) - npref, npref, manifest_path))
  message(sprintf("  script: %s", script_path))
  if (npref > 0L) {
    message("  running it moves the non-preferred copies out and leaves the ",
            "preferred
  ones where they are; --include-preferred relocates ",
            "those too.")
  }
  invisible(manifest)
}
