# Phase 3: translate paths and plan server-side moves.

#' Translate a Mac SMB path to its Synology server-side absolute path.
#'
#' @param path A path under `cfg$library_root` (the SMB mount).
#' @param cfg A config list (uses `library_root` and `nas_root`).
#' @return The server-side absolute path.
#' @export
dd_translate_path <- function(path, cfg) {
  if (is.null(cfg$nas_root) || is.null(cfg$library_root)) {
    stop("config: library_root and nas_root must be set to translate paths.")
  }
  root <- sub("/+$", "", cfg$library_root)
  nas  <- sub("/+$", "", cfg$nas_root)
  is_under <- startsWith(path, paste0(root, "/")) | path == root
  if (!all(is_under)) {
    stop("path(s) not under library_root: ",
         paste(utils::head(path[!is_under], 3L), collapse = ", "))
  }
  rel <- substring(path, nchar(root) + 2L)
  file.path(nas, rel)
}

#' Compute the destination (server-side) path for a photo.
#'
#' @param rel_path Path relative to the library root.
#' @param preferred Logical; TRUE routes to the preferred root.
#' @param cfg A config list (uses `preferred_root`, `nonpreferred_root`).
#' @return The destination absolute path, preserving the relative tree.
#' @export
dd_map_dest <- function(rel_path, preferred, cfg) {
  root <- ifelse(preferred, cfg$preferred_root, cfg$nonpreferred_root)
  file.path(root, rel_path)
}

#' Plan moves for all decided photos and emit a manifest + shell script.
#'
#' Writes nothing destructive: produces a TSV manifest, a reviewable NUL-safe
#' shell script of `mkdir -p`/`mv` commands (to be run server-side), and records
#' planned rows in the `moves` table. Re-runnable.
#'
#' @param con A DBIConnection.
#' @param cfg A config list.
#' @param manifest_path Output TSV path (default under `work_dir`).
#' @param script_path Output shell script path (default under `work_dir`).
#' @return The manifest data.frame, invisibly.
#' @export
dd_plan_moves <- function(con, cfg,
                          manifest_path = file.path(cfg$work_dir,
                                                    "moves.tsv"),
                          script_path = file.path(cfg$work_dir,
                                                  "moves.sh")) {
  dec <- DBI::dbGetQuery(con, "
    SELECT d.photo_id, d.preferred, p.path, p.rel_path
      FROM decisions d JOIN photos p USING (photo_id)
  ")
  if (nrow(dec) == 0L) {
    message("No decisions to plan.")
    return(invisible(dec[0, ]))
  }
  src  <- dd_translate_path(dec$path, cfg)
  dest <- dd_map_dest(dec$rel_path, dec$preferred == 1L, cfg)
  manifest <- data.frame(
    photo_id = dec$photo_id, preferred = dec$preferred,
    src = src, dest = dest, stringsAsFactors = FALSE
  )

  utils::write.table(manifest, manifest_path, sep = "\t", quote = FALSE,
                     row.names = FALSE)

  # Build a defensive shell script. Single-quote each path (escaping embedded
  # single quotes) so spaces/awkward characters are safe; skip if source is
  # already gone and dest exists (idempotent/resumable).
  shq <- function(x) paste0("'", gsub("'", "'\\\\''", x), "'")
  lines <- c(
    "#!/usr/bin/env bash",
    "# Generated by dundee dd_plan_moves(). Review before running server-side.",
    "set -euo pipefail",
    ""
  )
  for (i in seq_len(nrow(manifest))) {
    s <- shq(manifest$src[i]); d <- shq(manifest$dest[i])
    lines <- c(lines,
      sprintf("if [ -e %s ]; then mkdir -p \"$(dirname %s)\" && mv -n %s %s; fi",
              s, d, s, d))
  }
  writeLines(lines, script_path)
  Sys.chmod(script_path, "0755")

  # Record planned rows (idempotent upsert).
  dd_upsert(con, "moves",
            data.frame(photo_id = manifest$photo_id, src = manifest$src,
                       dest = manifest$dest, state = "planned",
                       moved_at = NA_character_, stringsAsFactors = FALSE),
            key_cols = "photo_id")

  message(sprintf("Planned %d moves -> %s (script: %s)",
                  nrow(manifest), manifest_path, script_path))
  invisible(manifest)
}
